---
title: "Optimisation of London data with SEIRD model"
author: "Chon Lok Lei and Hui Jia Farm"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(comomodels)
library(ggplot2)
library(gridExtra)
library(glue)
library(dplyr)
library(tidyr)
library(nloptr)
```

# Check for cached data
```{r bool-cached-data}
# TRUE to plot saved data, FALSE to run optimisation
cached_bool <- FALSE
set.seed(0)
```

## Optimisation on synthetic data (incidences and deaths)

## Simulate data

```{r setup-model, eval=!cached_bool}
model <- SEIRD()
simulating_para <- c(9.1e-1, 8.7e-1, 5.3e-1, 9.7e-2,
                     9.999e-1, 1e-7, 1e-7, 1e-6)

transmission_parameters(model) <- list(beta=simulating_para[1], 
                                       kappa=simulating_para[2],
                                       gamma=simulating_para[3], 
                                       mu=simulating_para[4])
initial_conditions(model) <- list(S0=simulating_para[5], E0=simulating_para[6],
                                  I0=simulating_para[7], R0=simulating_para[8])

times <- seq(0, 150, by = 1)
out_df <- run(model, times)
```

## Add noise to simulated data (incidences and deaths)

```{r add-noise, eval=!cached_bool}
population_size <- 1e4

# add noise
testing_data <- spread(out_df$changes, compartment, value)
testing_data$Incidence <- testing_data$Incidence * population_size
testing_data$Deaths <- testing_data$Deaths * population_size
inc_noise <- rpois(1, testing_data$Incidence[1])
death_noise <- rpois(1, testing_data$Deaths[1])
for (i in 2:length(testing_data$Incidence)){
  inc_rand <- rpois(1, testing_data$Incidence[i])
  inc_noise <- c(inc_noise, inc_rand)
  
  death_rand <- rpois(1, testing_data$Deaths[i])
  death_noise <- c(death_noise, death_rand)
}
testing_data$IncNoise <- inc_noise
testing_data$DeathNoise <- death_noise
testing_data <- testing_data[-1,]

# save results
# write.csv(testing_data, "synthetic_data.csv", row.names = FALSE)
```
```{r, eval=cached_bool}
population_size <- 1e4
testing_data <- read.csv("synthetic_data.csv")
```


## Visualise simulation

```{r plot-synthetic-data, fig.height = 5, fig.width = 7}
ggplot() +
  geom_line(data=testing_data, aes(x = time, y = DeathNoise, color = "Deaths")) +
  geom_line(data=testing_data, aes(x = time, y = IncNoise, color = "Incidence")) +
  scale_color_manual(name = "Cases", values = c("Incidence" = "red", "Deaths" = "blue")) +
  labs(x = "time (days)", y = "number of the population",
       title = glue("Evolution of different compartments over time"))
```

## Create error function

```{r error-fn}
ErrorFn <- function(parameters, model=SEIRD(), inc_numbers=0, death_numbers=0,
                    fixed_parameter=FALSE, fixed_parameter_value=0) {
  
  transmission_para <- list(beta=parameters[1],
                            kappa=parameters[2],
                            gamma=parameters[3],
                            mu=parameters[4])
  if (fixed_parameter != FALSE){
    transmission_para[names(transmission_para) == fixed_parameter] <- fixed_parameter_value}

  init_cond <- list(S0=parameters[5],
                    E0=parameters[6],
                    I0=parameters[7],
                    R0=parameters[8]) # 1-sum(parameters[5:7])
  
  transmission_parameters(model) <- transmission_para
  initial_conditions(model) <- init_cond
  
  times <- seq(0, length(inc_numbers), by = 1)
  out_df <- run(model, times)
  
  data_wide <- spread(out_df$changes, compartment, value)
  data_wide$Incidence <- abs(data_wide$Incidence) * population_size
  data_wide$Deaths <- abs(data_wide$Deaths) * population_size
  
  logIncidence <- log(data_wide$Incidence[-1])
  logIncidence[logIncidence == -Inf] <- -1
  incidence_likelihood <- sum(- inc_numbers * logIncidence + data_wide$Incidence[-1])
#  death_likelihood <- -sqrt(sum((death_numbers - data_wide$Deaths[-1])^2))
  logDeaths <- log(data_wide$Deaths[-1])
  logDeaths[logDeaths == -Inf] <- -1
  death_likelihood <- sum(- death_numbers * logDeaths + data_wide$Deaths[-1])

  (incidence_likelihood + death_likelihood)/2
}
```

## Optimisation

# Set up constraints and data structure for results

```{r constraints}
# set constraints
constraint_ui <- rbind(diag(8), -diag(8)[5:8,], c(rep(0, 4), rep(1,4)), c(rep(0, 4), rep(-1,4)))
constraint_ci <- c(rep(0, 8), rep(-1, 4), 0.99, -1.01)
```

# Run single optimisation

```{r single-opt}
init_guess <- c(0.9, 0.8, 0.5, 0.01, 0.997, 0.001, 0.001, 0.001)
#result <- constrOptim(init_guess, ErrorFn,
#                      'NULL', constraint_ui, constraint_ci,
#                      method = "Nelder-Mead", model=model,
#                      inc_numbers = testing_data$IncNoise, 
#                      death_numbers = testing_data$DeathNoise)
#heq <- function(x, model, inc_numbers, death_numbers, fixed_parameter, fixed_parameter_value){ 
#		sum(x[5:8]) - 1}
#heq <- function(x) {rbind(c(sum(x[5:8]) - 0.99, -sum(x[5:8])+1.01))}
heq <- function(x) {sum(x[5:8])-1}
result <- isres(x0=init_guess, fn=ErrorFn, lower=c(rep(0,8)), 
				upper=c(rep(1e6, 4), rep(1, 4)), heq=heq,
				nl.info=TRUE, #control=list(xtol_rel=1, maxeval=10000),
				model=model, inc_numbers=testing_data$IncNoise,
				death_numbers=testing_data$DeathNoise)					    
				# fixed_parameter=FALSE, fixed_parameter_value=0)					    
#result <- nloptr(x0=init_guess, eval_f=ErrorFn, lb=c(rep(0,8)),
#				 ub = c(rep(Inf, 4), rep(1,4)), eval_g_eq=heq,
#				 opts=list("algorithm"="NLOPT_LD_AUGLAG", local_opts=list(algorithm="NLOPT_LD_MMA")),
#			     model=model, inc_numbers=testing_data$IncNoise,
#				 death_numbers=testing_data$DeathNoise,
#				 fixed_parameter=FALSE, fixed_parameter_value=0)					    
print(result$par)
print(result$value)
print(result)
ErrorFn(simulating_para, model=model, inc_numbers=testing_data$IncNoise,
				death_numbers=testing_data$DeathNoise)					    

```

# Visualise optimisation result

```{r plot-opt, fig.height = 5, fig.width = 7}
parameters <- result$par
transmission_para <- list(beta=parameters[1],
                              kappa=parameters[2],
                              gamma=parameters[3],
                              mu=parameters[4])
init_cond <- list(S0=parameters[5],
                  E0=parameters[6],
                  I0=parameters[7],
                  R0=parameters[8])

transmission_parameters(model) <- transmission_para
initial_conditions(model) <- init_cond

times <- seq(0, length(testing_data$IncNoise), by = 1)
out_df <- run(model, times)

cases <- out_df$changes
cases <- spread(cases, compartment, value)
cases$Incidence <- cases$Incidence * population_size
cases$Deaths <- cases$Deaths * population_size

ggplot() +
  geom_line(data=cases, aes(x = time, y = Incidence, color="Optimised Incidence")) +
  geom_line(data=cases, aes(x = time, y = Deaths, color="Optimised Deaths")) +
  geom_line(data=testing_data, aes(x = time, y = IncNoise, color = "Simulated Incidence")) +
  geom_line(data=testing_data, aes(x = time, y = DeathNoise, color = "Simulated Deaths")) +
  scale_color_manual(name = "Legend", values = c("Optimised Incidence" = "red", "Optimised Deaths" = "blue", "Simulated Incidence" = "#FF6699", "Simulated Deaths" = "#66CCFF")) +
  labs(x = "time (days)", y = "fraction of the population",
       title = glue("Evolution of different compartments over time"))
```
