---
title: "Optimisation of London data with SEIRD model"
author: "Chon Lok Lei and Hui Jia Farm"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(comomodels)
library(ggplot2)
library(glue)
library(dplyr)
library(tidyr)
```

## Load London data
```{r}
# Depending on the working directory
# Yet to set a generic one
setwd("..")
df_london = read.csv('./data/London_data.csv', header = TRUE)

# Extracting cases and deaths and renaming columns
#London
cases_deaths_name_london = c('newCasesBySpecimenDate', 'newDailyNsoDeathsByDeathDate')
df_london = df_london[cases_deaths_name_london]
names(df_london)[names(df_london) == "newCasesBySpecimenDate"] <- "DailyCases"
names(df_london)[names(df_london) == "newDailyNsoDeathsByDeathDate"] <- "DailyDeaths"

London_population <- 9e6
```

Plot of London data
```{r, fig.height = 5, fig.width = 7}
# plot (df_london$DailyCases[42:82], type = 'l')
# plot (df_london$DailyDeaths[42:82], type = 'l')

London = df_london[42:82, 1:2] # Start of lockdown (23/03/2020) is 83rd day
print(head(London, 10))
rownames(London) = seq(length=nrow(London))
London$time <- seq(length=nrow(London))


ggplot() +
  geom_line(data=London, aes(x = time, y = DailyCases, color="Incidence")) +
  geom_line(data=London, aes(x = time, y = DailyDeaths, color="Deaths")) +
  scale_color_manual(name = "Legend", values = c("Incidence" = "#FF6699", "Deaths" = "#66CCFF")) +
  # scale_color_brewer(palette = "Dark2") +
  labs(x = "time (days)", y = "number of cases",
       title = glue("Incidences and deaths over time"))
```

## Create error function
```{r}
ErrorFn <- function(parameters) {
    
    transmission_para <- list(beta=parameters[1],
                              kappa=parameters[2],
                              gamma=parameters[3],
                              mu=parameters[4])
    init_cond <- list(S0=parameters[5],
                      E0=parameters[6],
                      I0=parameters[7],
                      R0=1-sum(parameters[5:7]))
    
    my_model <- SEIRD()
    
    transmission_parameters(my_model) <- transmission_para
    initial_conditions(my_model) <- init_cond
  
    times <- seq(0, length(London$DailyCases), by = 1)
    out_df <- run(my_model, times)
    
    data_wide <- spread(out_df$changes, compartment, value)
    data_wide$Incidence <- data_wide$Incidence * London_population
    data_wide$Deaths <- data_wide$Deaths * London_population
    
    incidence_err <- sqrt(sum((London$DailyCases - data_wide$Incidence[-1])^2))
    death_err <- sqrt(sum((London$DailyDeaths - data_wide$Deaths[-1])^2))
    
    (incidence_err + death_err)/2
}
```

## Optimisation
```{r}
trans_params_guess <- c(0.35, 0.1, 0.05, 0.05)
init_conds_guess<- c(1-3e-7, 1e-7, 1e-7, 1e-7)
constraint_ui <- rbind(diag(8), -diag(8), c(rep(0, 4), rep(1,4)), c(rep(0, 4), rep(-1,4)))
constraint_ci <- c(rep(0, 8), rep(-1, 8), 0.99, -1.01)

result <- constrOptim(c(trans_params_guess, init_conds_guess), ErrorFn,
            'NULL', constraint_ui, constraint_ci,
            method = "Nelder-Mead")
result$value
```

```{r, fig.height = 5, fig.width = 7}
parameters1 <- result$par
transmission_para <- list(beta=parameters1[1],
                              kappa=parameters1[2],
                              gamma=parameters1[3],
                              mu=parameters1[4])
init_cond <- list(S0=parameters1[5],
                  E0=parameters1[6],
                  I0=parameters1[7],
                  R0=parameters1[8])

my_model <- SEIRD()
    
transmission_parameters(my_model) <- transmission_para
initial_conditions(my_model) <- init_cond

times <- seq(0, length(London$DailyCases), by = 1)
out_df <- run(my_model, times)

cases <- out_df$changes
cases <- spread(cases, compartment, value)
cases$Incidence <- cases$Incidence * London_population
cases$Deaths <- cases$Deaths * London_population
cases <- cases[-1,]

London$time <- cases$time[1:length(London$DailyCases)]

ggplot() +
  geom_line(data=cases, aes(x = time, y = Incidence, color="Optimised Incidence")) +
  geom_line(data=cases, aes(x = time, y = Deaths, color="Optimised Deaths")) +
  geom_line(data=London, aes(x = time, y = DailyCases, color = "Actual Incidence")) +
  geom_line(data=London, aes(x = time, y = DailyDeaths, color = "Actual Deaths")) +
  scale_color_manual(name = "Legend", values = c("Optimised Incidence" = "red", "Optimised Deaths" = "blue", "Actual Incidence" = "#FF6699", "Actual Deaths" = "#66CCFF")) +
  # scale_color_brewer(palette = "Dark2") +
  labs(x = "time (days)", y = "number of cases",
       title = glue("Incidences and deaths over time"))
```

```{r}
parameters1
```

## Future projection
```{r, fig.height = 5, fig.width = 7}
times <- seq(0, 100, by = 1)
out_df <- run(my_model, times)

cases <- out_df$changes
cases <- spread(cases, compartment, value)
cases$Incidence <- cases$Incidence * London_population
cases$Deaths <- cases$Deaths * London_population
cases <- cases[-1,]

ggplot() +
  geom_line(data=cases, aes(x = time, y = Incidence, color="Optimised Incidence")) +
  geom_line(data=cases, aes(x = time, y = Deaths, color="Optimised Deaths")) +
  scale_color_manual(name = "Legend", values = c("Optimised Incidence" = "red", "Optimised Deaths" = "blue")) +
  # scale_color_brewer(palette = "Dark2") +
  labs(x = "time (days)", y = "number of cases",
       title = glue("Incidences and deaths over time"))
```

## Optimisation2
```{r}
trans_params_guess <- c(0.5, 0.5, 0.2, 0.2)
init_conds_guess<- c(1-3e-7, 1e-7, 1e-7, 1e-7)
constraint_ui <- rbind(diag(8), -diag(8), c(rep(0, 4), rep(1,4)), c(rep(0, 4), rep(-1,4)))
constraint_ci <- c(rep(0, 8), rep(-1, 8), 0.99, -1.01)

result <- constrOptim(c(trans_params_guess, init_conds_guess), ErrorFn,
            'NULL', constraint_ui, constraint_ci,
            method = "Nelder-Mead")
result$value
```

```{r, fig.height = 5, fig.width = 7}
parameters2 <- result$par
transmission_para <- list(beta=parameters2[1],
                              kappa=parameters2[2],
                              gamma=parameters2[3],
                              mu=parameters2[4])
init_cond <- list(S0=parameters2[5],
                  E0=parameters2[6],
                  I0=parameters2[7],
                  R0=parameters2[8])

my_model <- SEIRD()
    
transmission_parameters(my_model) <- transmission_para
initial_conditions(my_model) <- init_cond

times <- seq(0, length(London$DailyCases), by = 1)
out_df <- run(my_model, times)

cases <- out_df$changes
cases <- spread(cases, compartment, value)
cases$Incidence <- cases$Incidence * London_population
cases$Deaths <- cases$Deaths * London_population
cases <- cases[-1,]

London$time <- cases$time[1:length(London$DailyCases)]

ggplot() +
  geom_line(data=cases, aes(x = time, y = Incidence, color="Optimised Incidence")) +
  geom_line(data=cases, aes(x = time, y = Deaths, color="Optimised Deaths")) +
  geom_line(data=London, aes(x = time, y = DailyCases, color = "Actual Incidence")) +
  geom_line(data=London, aes(x = time, y = DailyDeaths, color = "Actual Deaths")) +
  scale_color_manual(name = "Legend", values = c("Optimised Incidence" = "red", "Optimised Deaths" = "blue", "Actual Incidence" = "#FF6699", "Actual Deaths" = "#66CCFF")) +
  # scale_color_brewer(palette = "Dark2") +
  labs(x = "time (days)", y = "number of cases",
       title = glue("Incidences and deaths over time"))
```

```{r}
parameters2
```

## Future projection
```{r, fig.height = 5, fig.width = 7}
times <- seq(0, 100, by = 1)
out_df <- run(my_model, times)

cases <- out_df$changes
cases <- spread(cases, compartment, value)
cases$Incidence <- cases$Incidence * London_population
cases$Deaths <- cases$Deaths * London_population
cases <- cases[-1,]

ggplot() +
  geom_line(data=cases, aes(x = time, y = Incidence, color="Optimised Incidence")) +
  geom_line(data=cases, aes(x = time, y = Deaths, color="Optimised Deaths")) +
  scale_color_manual(name = "Legend", values = c("Optimised Incidence" = "red", "Optimised Deaths" = "blue")) +
  # scale_color_brewer(palette = "Dark2") +
  labs(x = "time (days)", y = "number of cases",
       title = glue("Incidences and deaths over time"))
```

## Comparison of 2 sets of parameters
```{r}
simulation <- function(parameters, time_length){
    transmission_para <- list(beta=parameters[1],
                                  kappa=parameters[2],
                                  gamma=parameters[3],
                                  mu=parameters[4])
    init_cond <- list(S0=parameters[5],
                      E0=parameters[6],
                      I0=parameters[7],
                      R0=parameters[8])
    
    my_model <- SEIRD()
        
    transmission_parameters(my_model) <- transmission_para
    initial_conditions(my_model) <- init_cond
    
    times <- seq(0, time_length, by = 1)
    out_df <- run(my_model, times)
    
    cases <- out_df$changes
    cases <- spread(cases, compartment, value)
    cases$Incidence <- cases$Incidence * London_population
    cases$Deaths <- cases$Deaths * London_population
    cases[-1,]
}
```

```{r}
# parameters1 <- c(4.056747e-01, 2.053301e-01, 5.508388e-02, 4.359358e-02, 9.999993e-01, 5.095259e-07, 4.340775e-07, 1.972826e-06)
# parameters2 <- c(5.422729e-01, 6.137988e-01, 2.407549e-01, 5.832852e-02, 9.999996e-01, 2.826537e-07, 2.680777e-07, 1.824414e-07)

cases1 <- simulation(parameters1, 200)
cases2 <- simulation(parameters2, 200)
```

```{r, fig.height = 5, fig.width = 7}
ggplot() +
  geom_line(data=cases1, aes(x = time, y = Incidence, color="Optimised Incidence")) +
  geom_line(data=cases1, aes(x = time, y = Deaths, color="Optimised Deaths")) +
  geom_line(data=cases2, aes(x = time, y = Incidence, color="Optimised Incidence 2")) +
  geom_line(data=cases2, aes(x = time, y = Deaths, color="Optimised Deaths 2")) +
  scale_color_manual(name = "Legend", values = c("Optimised Incidence" = "red", "Optimised Deaths" = "blue", "Optimised Incidence 2" = "#FF6699", "Optimised Deaths 2" = "#66CCFF")) +
  # scale_color_brewer(palette = "Dark2") +
  labs(x = "time (days)", y = "number of cases",
       title = glue("Incidences and deaths over time"))
```
