name: "Unit tests: Windows"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:

  test:
    name: tests on Ubuntu with R ${{ matrix.R }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        R: [ '3.6.3', '4.0.4' ]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.R }}
          Ncpus: 2
          
      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}
        
      - name: cache R installed packages
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-R${{ matrix.R }}-2-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-R${{ matrix.R }}-2-
      
      - name: Install packages
        run: |
          install.packages(c("devtools"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}

      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: |
          options(crayon.enabled = TRUE)
          rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      - name: Show testthat output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash
